# Generated by Django 2.0.5 on 2018-05-12 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arduino_id', models.IntegerField(verbose_name='ID no Arduino')),
                ('song_title', models.CharField(max_length=200, verbose_name='título')),
                ('song_interpret', models.CharField(max_length=200, verbose_name='intérprete')),
                ('song_album', models.CharField(max_length=200, verbose_name='álbum')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_title', models.CharField(max_length=200, verbose_name='nome')),
                ('creation_date', models.DateTimeField(verbose_name='data de criação')),
            ],
        ),
        migrations.AddField(
            model_name='musica',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autofalante.Playlist'),
        ),
    ]
