# Generated by Django 2.0.5 on 2018-05-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autofalante', '0002_musica_executing'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='data de modificação'),
        ),
    ]
