# Generated by Django 2.0.5 on 2018-05-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autofalante', '0003_musica_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='in_line',
            field=models.BooleanField(default=0, editable=False, verbose_name='Na fila de execução'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musica',
            name='executing',
            field=models.BooleanField(editable=False, verbose_name='Execução imediata'),
        ),
    ]
