# Generated by Django 2.0.6 on 2018-06-06 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autofalante', '0005_auto_20180528_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlists', models.ManyToManyField(to='autofalante.Playlist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='musica',
            name='execute',
            field=models.BooleanField(verbose_name='Execução foi pedida'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='in_line',
            field=models.BooleanField(verbose_name='Na fila de execução'),
        ),
    ]
