# Generated by Django 2.0 on 2018-06-09 23:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('autofalante', '0007_playlist_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 9, 23, 13, 43, 668088, tzinfo=utc), verbose_name='data de criação'),
        ),
    ]
